name: json_converter_helper
description: JSON converters for package:json_serializable.
version: 0.1.3
repository: https://github.com/mono0926/json_converter_helper

environment:
  sdk: ^3.0.0

dependencies:
  cloud_firestore: ^5.0.0
  freezed_annotation: ^2.0.3
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner:
  fake_cloud_firestore:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:
  test:
